<?php
$this->RenderCss('/Sources/Product/Css/Index');
?>
<div class="DirectorContainer">
    <div class="HeadLeft">
        <div class="SupportActionContainer">
            <button class="SupportAction">Map</button>
            <button class="SupportAction">Create</button>
            <button class="SupportAction">Your product</button>
            <button class="SupportAction">Your follow</button>
            <button class="SupportAction">Manual</button>
            <button class="SupportAction">Main</button>
            <button class="SupportAction">Home</button>
        </div>        
    </div>
    <div class="HeadRight">
        <div class="SearchContainer">
            <div class="InputContainer">
                <div class="InputIcon">
                    <img src="/Sources/Community/Img/Search.png" />
                </div>  
                <div class="Input">
                    <input type="text" placeholder="What do you want product"/>
                </div>                                                          
            </div>          
        </div>        
    </div>
</div>
<div class="Active">
    <span>Current your active: </span>Main
</div>
<div class="ProductList">
    <?php foreach($this->Data['Products'] as $Product) {?>
    <div class="ProductContainer">
        <img src="/Sources/Product/Img/Cover/<?php echo $Product['Id']?>.png">
        <div class="ProductName">
            <?php echo $Product['Name']?>
        </div>
    </div>
    <?php }?>
</div>
<?php
$this->RenderJs('/Sources/Product/Js/Index');