<?php
$this->RenderCss('/Sources/Support/Css/Index');
?>
<div class="DirectorContainer">
    <div class="HeadLeft">
        <div class="SupportActionContainer">
            <button class="SupportAction">Question</button>
            <button class="SupportAction">Find bug</button>
            <button class="SupportAction">Feedback</button>
            <button class="SupportAction">Meeting</button>
            <button class="SupportAction">Donate</button>
            <button class="SupportAction">Manual</button>
            <button class="SupportAction">Main</button>
            <button class="SupportAction">Home</button>
        </div>        
    </div>
    <div class="HeadRight">
        <div class="SearchContainer">
            <div class="InputContainer">
                <div class="InputIcon">
                    <img src="/Sources/Community/Img/Search.png" />
                </div>  
                <div class="Input">
                    <input type="text" placeholder="What's your problem"/>
                </div>                                                          
            </div>          
        </div>        
    </div>
</div>
<div class="Active">
    <span>Current your active: </span>Main
</div>
<div class="ContentContainer">
    <div class="Content" id="Index">
        <?php foreach ($this->Data['Support'] as $TypeName => $Articles) {?>  
        <div class="SlideWraper">
            <div class="TypeSupport"><?php echo $TypeName?></div>
            <div class="SlideContainer">
                <?php foreach ($Articles as $Article) {?>
                <div class="Slide">
                    <div class="LeftContent">
                        <a href="/Article/Read/Single?Id=<?php echo $Article['Id']?>" target="_blank">
                            <img src="/Sources/Article/Img/Cover/<?php echo $Article['Id']?>.png">
                        </a>
                    </div>
                    <div class="RightContent">
                        <div class="ArticleTitle"><?php echo $Article['Name']?></div>
                        <div class="ArticleContent"><?php echo $Article['Contents']?></div>                
                    </div> 
                    
                </div>
                <?php }?>
            </div>           
        </div>
        <?php }?>
    </div>
</div>
<?php
$this->RenderCss('/Sources/Support/Css/Index');