<?php
$this->RenderCss('/Sources/Article/Css/Index');
?>
<div class="DirectorContainer">
    <div class="HeadLeft">
        <div class="SupportActionContainer">
            <button class="SupportAction" id="Map">Map</button>
            <button class="SupportAction" id="Center">Center</button>
            <button class="SupportAction" id="Write">Write</button>
            <button class="SupportAction" id="YourArticle">Your article</button>
            <button class="SupportAction" id="YourFollow">Your follow</button>
            <button class="SupportAction" id="Manual">Manual</button>            
            <button class="SupportAction" id="Home">Home</button>
        </div>        
    </div>
    <div class="HeadRight">
        <div class="SearchContainer">
            <div class="InputContainer">
                <div class="InputIcon">
                    <img src="/Sources/Community/Img/Search.png" />
                </div>  
                <div class="Input">
                    <input type="text" placeholder="What do you want article"/>
                </div>                                                          
            </div>          
        </div>        
    </div>
</div>
<div class="Active">
    <span>Current your active: </span>Main
</div>
<div class="Content" id="CenterContent">
    <div class="BestArticle">
        <div class="ListTitle">Excellent article</div>
        <?php foreach ($this->Data['ExcellentArticle'] as $ExcArticle) {?>
        <div class="ArticleContainer">
            <div class="LeftContent">
                <div class="WideCoverArticle">
                    <a href="/Article/Read/Single?Id=<?php echo $ExcArticle['Id']?>" target="_blank">
                        <img src="/Sources/Article/Img/WideCover/<?php echo $ExcArticle['Id']?>.png">
                    </a>
                </div>            
            </div>
            <div class="RightContent">
                <div class="ArticleTitle">
                    <?php echo $ExcArticle['Name']?>
                </div>
                <div class="ArticleContent">
                    <?php echo nl2br($ExcArticle['Contents'])?>
                </div>
            </div>
        </div>
        <?php }?>
    </div>    
    <div class="ClassArticle">
        <div class="ListTitle">Best article</div>
        <?php foreach ($this->Data['Class'] as $Type => $Articles) {?>
            <div class="ArticleChoseContainer">
                <div class="ArticleListTitile">
                    <?php echo $Type?> 
                </div> 
                <!--Hide rest article but show title-->
                <?php $Display = FALSE?>
                <?php foreach ($Articles as $Article) {?>
                <div class="ArticleSummaryContainer">
                    <div class="ArticleTitleChose">
                        <?php echo $Article['Name']?>                      
                    </div>           
                    <div class="ArticleContentChose" <?php if(!$Display) {echo 'style="display:block"'; $Display = TRUE;}?>>
                        <div class="MiniLeftContent">
                            <?php echo nl2br($Article['Contents'])?>
                        </div>
                        <div class="MiniRightContent">
                            <a href="/Article/Read/Single?Id=<?php echo $Article['Id']?>" target="_blank"><img src="/Sources/Article/Img/Cover/<?php echo $Article['Id']?>.png"></a>
                        </div>                        
                        
                    </div>                     
                </div>
                <?php }?>
            </div>  
        <?php }?>
    </div>    
</div>
<div class="Content" id="DynamicContent" style="display: none">
    
</div>
<?php
$this->RenderJs('/Sources/Article/Js/Index');